apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-details-role
rules:
  - apiGroups: ["apps"]
    resources: ["deployments", "replicasets"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["pods", "services"]
    verbs: ["get", "list"]
  - apiGroups: [ "batch" ]
    resources: [ "jobs" ]
    verbs: [ "get", "list", "create" ]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-details-rolebinding
subjects:
  - kind: ServiceAccount
    name: cluster-deets-sa
    namespace: default
roleRef:
  kind: ClusterRole
  name: cluster-details-role
  apiGroup: rbac.authorization.k8s.io


---


#apiVersion: rbac.authorization.k8s.io/v1
#kind: Role
#metadata:
#  namespace: default  # Change if your app is in a different namespace
#  name: cluster-details-role
#rules:
#  - apiGroups: [""]
#    resources: ["pods", "services"]
#    verbs: ["get", "list"]
#  - apiGroups: ["apps"]
#    resources: ["deployments"]
#    verbs: ["get", "list"]
#
#
#---
#
#
#apiVersion: rbac.authorization.k8s.io/v1
#kind: RoleBinding
#metadata:
#  name: cluster-details-rolebinding
#  namespace: default
#subjects:
#  - kind: ServiceAccount
#    name: default  # Change if using a different service account
#    namespace: default
#roleRef:
#  kind: Role
#  name: cluster-details-role
#  apiGroup: rbac.authorization.k8s.io
#
#
#---

